//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace training.DiceRollGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("training.DiceRollGame.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

    /// <summary>
    ///   Looks up a localized string similar to Enter a number:.
    /// </summary>
    public static string EnterNumberMessage {
            get {
                return ResourceManager.GetString("EnterNumberMessage", resourceCulture);
            }
        }

    /// <summary>
    ///   Looks up a localized string similar to 3.
    /// </summary>
    public static string InitialTries {
            get {
                return ResourceManager.GetString("InitialTries", resourceCulture);
            }
        }

    /// <summary>
    ///   Looks up a localized string similar to You lose..
    /// </summary>
    public static string LossMessage {
            get {
                return ResourceManager.GetString("LossMessage", resourceCulture);
            }
        }

    /// <summary>
    ///   Looks up a localized string similar to You win!.
    /// </summary>
    public static string VictoryMessage {
            get {
                return ResourceManager.GetString("VictoryMessage", resourceCulture);
            }
        }

    /// <summary>
    ///   Looks up a localized string similar to Dice rolled. Guess the number in {0} tries..
    /// </summary>
    public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }

    /// <summary>
    ///   Looks up a localized string similar to Wrong number!.
    /// </summary>
    public static string WrongNumberMessage {
            get {
                return ResourceManager.GetString("WrongNumberMessage", resourceCulture);
            }
        }
    }
}
